volumes:
  db_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db_data:/home/app/db_data
    command: ["python3.13", "main.py"]
