"""initial migration

Revision ID: 095767fcb6bd
Revises:
Create Date: 2025-06-08 22:07:12.412963

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '095767fcb6bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'prompts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('text', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_prompt_name'),
    )
    op.create_table(
        'words',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('word', sa.String(length=500), nullable=True),
        sa.Column('transcription', sa.String(length=500), nullable=True),
        sa.Column('translation', sa.String(length=500), nullable=True),
        sa.Column('part_of_speech', sa.String(length=100), nullable=True),
        sa.Column('forms', sa.Text(), nullable=True),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('word'),
    )
    op.create_table(
        'examples',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('example', sa.Text(), nullable=True),
        sa.Column('translation', sa.Text(), nullable=True),
        sa.Column('word_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examples')
    op.drop_table('words')
    op.drop_table('prompts')
    # ### end Alembic commands ###
